# Generated by Django 6.0.3 on 2026-04-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.URLField(default=''),
        ),
    ]
